

#激活配置文件/需要制定其他的配置文件名称
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
    password: 8156v
  redis:
    host: 192.168.44.128
    port: 6379

#tomcat端口
server:
  port: 8080
#日志记录级别
logging:
  level:
    com.liysh: debug
    org.springframework: info
# mybatis配置
mybatis:
# 配置实体类别名包路径
  type-aliases-package: com.liysh.pojo
# 映射文件路径
# mapper-locations: classpath:mappers/*.xml
  configuration:
# 控制台输出执行sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
